# -*- coding: utf-8 -*-
"""Lista 1 (oito execícios)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ek4S2I2dvMxQGnOCrpqc8-kiHUh-AnMV
"""

# -*- coding: utf-8 -*-
"""
Questão 3 - Resolução de Sistema Linear 2x2
Autores: Mateus Nascimento Bueno, Marco Antonio Chaves Morbach
"""

import numpy as np

A = np.array([[2, 1],
              [1, 3]])
B = np.array([[5],
              [10]])

print("Matriz A:\n", A)
print("Matriz B:\n", B)

det_A = np.linalg.det(A)
if det_A == 0:
    print("O sistema não possui solução única.")
else:
    print(f"Determinante: {det_A}")
    A_inv = np.linalg.inv(A)
    Res = np.dot(A_inv, B)
    print("Solução do sistema (X e Y):\n", Res)