# -*- coding: utf-8 -*-
"""Lista 1 (oito execícios)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ek4S2I2dvMxQGnOCrpqc8-kiHUh-AnMV
"""

# -*- coding: utf-8 -*-
"""
Questão 6 - Soma de Linhas e Colunas
Autores: Mateus Nascimento Bueno, Marco Antonio Chaves Morbach
"""

import numpy as np

vendas_lojas = np.array([[100, 200, 150],
                         [80, 120, 100],
                         [90, 60, 110]])

# Soma por linha
soma_linha = np.sum(vendas_lojas, axis=1)
print("Total por loja:")
for i, total in enumerate(soma_linha, 1):
    print(f"Loja {i}: {total}")

# Soma por coluna
soma_coluna = np.sum(vendas_lojas, axis=0)
print("\nTotal por dia:")
for i, total in enumerate(soma_coluna, 1):
    print(f"Dia {i}: {total}")