# -*- coding: utf-8 -*-
"""Lista 1 (oito execícios)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ek4S2I2dvMxQGnOCrpqc8-kiHUh-AnMV
"""

# -*- coding: utf-8 -*-
"""
Questão 7 - Operações com Matrizes de Produção
Autores: Mateus Nascimento Bueno, Marco Antonio Chaves Morbach
"""

import numpy as np

janeiro = np.array([[50, 40],
                    [30, 20]])
fevereiro = np.array([[60, 32],
                      [25, 30]])

soma_meses = janeiro + fevereiro
print("Soma das produções:\n", soma_meses)
print("Produção total do bimestre:", np.sum(soma_meses))

# Multiplicação por matriz escalar
matriz_escalar = np.array([2, 3])
matriz_resultante = soma_meses * matriz_escalar
print("Matriz resultante após multiplicação escalar:\n", matriz_resultante)