# -*- coding: utf-8 -*-
"""Lista 1 (oito execícios)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ek4S2I2dvMxQGnOCrpqc8-kiHUh-AnMV
"""

# -*- coding: utf-8 -*-
"""
Questão 8 - Resolução de Sistema Linear 3x3
Autores: Mateus Nascimento Bueno, Marco Antonio Chaves Morbach
"""

import numpy as np

M_coef = np.array([[1, 1, 0],
                   [0, 2, 1],
                   [1, 1, 1]])
M_termos = np.array([[18],
                     [20],
                     [25]])

det_M = np.linalg.det(M_coef)
if det_M == 0:
    print("Sistema não possui solução única.")
else:
    print("Determinante:", det_M)
    M_inv = np.linalg.inv(M_coef)
    Res = np.dot(M_inv, M_termos)
    print("Solução do sistema (X, Y, Z):\n", Res)