# -*- coding: utf-8 -*-
"""Lista 1 (oito execícios)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ek4S2I2dvMxQGnOCrpqc8-kiHUh-AnMV
"""

# -*- coding: utf-8 -*-
"""
Questão 5 - Lucro Total usando Produto Escalar
Autores: Mateus Nascimento Bueno, Marco Antonio Chaves Morbach
"""

import numpy as np

vendas = np.array([50, 30, 20])
precos = np.array([10, 20, 30])

lucro_total = np.dot(vendas, precos)
print("Vendas:", vendas)
print("Preços:", precos)
print("Lucro total:", lucro_total)