# -*- coding: utf-8 -*-
"""Lista 1 (oito execícios)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ek4S2I2dvMxQGnOCrpqc8-kiHUh-AnMV
"""

# -*- coding: utf-8 -*-
"""
Questão 2 - Matriz Aleatória 3x3 e Transposta
Autores: Mateus Nascimento Bueno, Marco Antonio Chaves Morbach
"""

import numpy as np
from random import randint

# Criando matriz 3x3 com valores aleatórios de 0 a 255
M_aleatoria = np.array([[randint(0, 256) for _ in range(3)] for _ in range(3)])
print("Matriz aleatória 3x3:\n", M_aleatoria)

# Criando a matriz transposta
M_transposta = M_aleatoria.T
print("Matriz transposta:\n", M_transposta)