# -*- coding: utf-8 -*-
"""Lista 1 (oito execícios)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ek4S2I2dvMxQGnOCrpqc8-kiHUh-AnMV
"""

# -*- coding: utf-8 -*-
"""
Questão 1 - Multiplicação de Matrizes
Autores: Mateus Nascimento Bueno, Marco Antonio Chaves Morbach
"""

import numpy as np

# Matriz M (3x2)
M = np.array([[2, 3],
              [1, 4],
              [5, 2]])

# Matriz C (2x1)
C = np.array([[10],
              [20]])

print("Matriz M:\n", M)
print("Matriz C:\n", C)

# Multiplicação das matrizes
try:
    R = np.dot(M, C)
    print("Resultado da multiplicação:\n", R)
except ValueError as e:
    print("Erro na multiplicação:", e)