# -*- coding: utf-8 -*-
"""Lista 1 (oito execícios)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ek4S2I2dvMxQGnOCrpqc8-kiHUh-AnMV
"""

# -*- coding: utf-8 -*-
"""
Questão 4 - Área de Triângulo a partir de Coordenadas
Autores: Mateus Nascimento Bueno, Marco Antonio Chaves Morbach
"""

import numpy as np

# Coordenadas do triângulo
M_triangulo = np.array([[1, 2, 1],
                        [4, 6, 1],
                        [5, 3, 1]])

determinante = np.linalg.det(M_triangulo)
area = abs(determinante) / 2

print("Determinante:", determinante)
print("Área do triângulo:", area)